#pragma once

#include <Arduino.h>
#include <TFT_eSPI.h>
#include <lvgl.h>

#include "../logger/logger.h"

/**
 * @class DisplayManager
 * @brief Manages the physical display and LVGL display interface.
 *
 * The DisplayManager is responsible for initializing the physical
 * TFT display and connecting it to LVGL.
 *
 * Higher-level user interface components should use LVGL to draw
 * interface elements. They should not communicate directly with
 * TFT_eSPI.
 *
 * Responsibilities
 * ----------------
 * - Initialize the TFT display hardware.
 * - Initialize LVGL.
 * - Register the display with LVGL.
 * - Transfer LVGL render data to the physical display.
 * - Process LVGL updates.
 *
 * Example
 * -------
 * @code
 * DisplayManager display(logger);
 *
 * if (display.start())
 * {
 *     lv_obj_t* label = lv_label_create(lv_screen_active());
 *     lv_label_set_text(label, "Ch3rryB0mb");
 *     lv_obj_center(label);
 * }
 *
 * void loop()
 * {
 *     display.update();
 * }
 * @endcode
 */
class DisplayManager
{
public:
    /**
     * @brief Constructs a new DisplayManager.
     *
     * @param logger Reference to the application Logger.
     */
    explicit DisplayManager(Logger& logger);

    /**
     * @brief Initializes the display hardware and LVGL.
     *
     * Initializes the TFT display and configures LVGL so that
     * rendered content can be transferred to the physical screen.
     *
     * Example
     * -------
     * @code
     * if (!display.start())
     * {
     *     logger.error("Failed to start DisplayManager.");
     * }
     * @endcode
     *
     * @return true if the display initialized successfully.
     * @return false otherwise.
     */
    bool start();

    /**
     * @brief Processes LVGL display updates.
     *
     * This method should be called repeatedly from the application's
     * main update loop while the display is running.
     *
     * Example
     * -------
     * @code
     * if (display.isRunning())
     * {
     *     display.update();
     * }
     * @endcode
     */
    void update();

    /**
     * @brief Returns whether the display is initialized.
     *
     * Example
     * -------
     * @code
     * if (display.isRunning())
     * {
     *     logger.info("Display is ready.");
     * }
     * @endcode
     *
     * @return true if the display is initialized.
     * @return false otherwise.
     */
    bool isRunning() const;

private:
    /**
     * @brief Transfers rendered LVGL pixels to the physical display.
     *
     * This callback is called by LVGL whenever a rendered area
     * needs to be written to the TFT display.
     *
     * @param display LVGL display requesting the transfer.
     * @param area Area of the display that needs to be updated.
     * @param pxMap Pixel data generated by LVGL.
     */
    static void flushDisplay(
        lv_display_t* display,
        const lv_area_t* area,
        uint8_t* pxMap
    );

    /**
     * @brief Indicates whether the display is initialized.
     */
    bool running = false;

    /**
     * @brief Reference to the application Logger.
     */
    Logger& logger;

    /**
     * @brief Physical TFT display interface.
     *
     * TFT_eSPI is only used by the DisplayManager. Higher-level
     * UI code should use LVGL instead.
     */
    TFT_eSPI tft;
};