; PlatformIO Project Configuration File

[platformio]
boards_dir = custom_boards
default_envs = esp32-2432S028Y


; ---------------------------------------------------------------------------
; Shared settings
; ---------------------------------------------------------------------------

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.34/platform-espressif32.zip
framework = arduino

lib_deps =
    ; NRF
    nrf24/RF24@^1.6.1
    greiman/DigitalIO

    ; CC1101
    jgromes/RadioLib

    ; BLE
    h2zero/NimBLE-Arduino@2.5.1


; ---------------------------------------------------------------------------
; Ch3rryB0mb - CYD
; ---------------------------------------------------------------------------

[env:esp32-2432S028Y]
board = esp32-2432S028Y
board_build.partitions = huge_app.csv

upload_port = COM3
monitor_port = COM3

lib_deps =
    ${env.lib_deps}
    lvgl/lvgl@9.2.2

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
    -D CH3RRY_C3B0

build_src_filter =
    +<*>
    -<node/>


; ---------------------------------------------------------------------------
; Ch3rryN0de - ESP32-S3
; ---------------------------------------------------------------------------

[env:c3n0-s3]
board = esp32-s3-devkitc-1

upload_port = COM19
monitor_port = COM19

lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

build_flags =
    -I include
    -D C3N0_S3

build_src_filter =
    -<*>

    ; Node firmware
    +<node/>

    ; Shared hardware services
    +<services/logger/>
    +<services/spi/>
    +<services/nrf/>
    +<services/cc1101/>
    +<services/BLE/>

lib_ignore =
    esp32_smartdisplay