; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = custom_boards

[env:esp32-2432S028Y]
platform = espressif32
board = esp32-2432S028Y
framework = arduino

lib_deps =
    lvgl/lvgl@9.2.2
    nrf24/RF24@^1.6.1
    greiman/DigitalIO
    jgromes/RadioLib

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I include