; PlatformIO Project Configuration File

[platformio]
boards_dir = custom_boards
default_envs = esp32-2432S028Y


; ---------------------------------------------------------------------------
; Shared settings
; ---------------------------------------------------------------------------

[env]
platform = espressif32
framework = arduino

lib_deps =
    ; NRF
    nrf24/RF24@^1.6.1
    greiman/DigitalIO

    ; CC1101
    jgromes/RadioLib

    ; BLE
    h2zero/NimBLE-Arduino@^2.1.0


; ---------------------------------------------------------------------------
; Ch3rryB0mb - CYD
; ---------------------------------------------------------------------------

[env:esp32-2432S028Y]
board = esp32-2432S028Y
board_build.partitions = huge_app.csv

lib_deps =
    ${env.lib_deps}
    lvgl/lvgl@9.2.2

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
    -D CH3RRY_C3B0

build_src_filter =
    +<*>
    -<node/>


; ---------------------------------------------------------------------------
; Ch3rryN0de - ESP32 WROOM
; ---------------------------------------------------------------------------

[env:c3n0]
board = esp32dev

lib_deps =
    ${env.lib_deps}
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

build_flags =
    -I include
    -D CH3RRY_NODE

build_src_filter =
    -<*>

    ; Node firmware
    +<node/>

    ; Shared hardware services
    +<services/logger/>
    +<services/spi/>
    +<services/nrf/>
    +<services/cc1101/>
    +<services/BLE/>

lib_ignore =
    esp32_smartdisplay