#pragma once

//v1
//input actions that can be performed by the user. 
//These are used to represent the different types of input events that can be generated by the input system
//For now no more actions are needed, but in the future more actions can be added to this enum class
enum class InputAction {
    Up,
    Down,
    Left,
    Right,
    Select,
    Back,
    Menu
};