#pragma once

#include "InputAction.h"

//v1
//Different input event types that can be generated by the input system.
enum class InputEventType {
    Pressed,
    Released,
    LongPressed
};

//The input event struct that is used to represent an input event that has been generated by the input system.
struct InputEvent {
    InputAction action;
    InputEventType type;
};